import { THEME } from './theme';
import { CONTENT_X, CONTENT_WIDTH, CONTENT_Y_AFTER_HEADER } from './geometry';

export const COVER_LAYOUT = {
  LABEL_X: CONTENT_X,
  LABEL_Y: 0.62,
  LABEL_W: 6.4,
  LABEL_H: 0.2,
  TITLE_X: CONTENT_X,
  TITLE_Y: 1.55,
  TITLE_W: 6.35,
  TITLE_H: 1.55,
  STRIP_X: 8.24,
  STRIP_Y: 0,
  STRIP_W: THEME.SLIDE_WIDTH - 8.24,
  STRIP_H: THEME.SLIDE_HEIGHT,
  ACCENT_X: CONTENT_X,
  ACCENT_W: 0.46,
} as const;

export const OVERVIEW_LAYOUT = {
  TITLE_X: CONTENT_X,
  TITLE_Y: 1.18,
  TITLE_W: 6.8,
  TITLE_H: 0.72,
  DIVIDER_Y: 2.02,
  LEFT_COL_X: CONTENT_X,
  LEFT_COL_W: 7.25,
  RIGHT_COL_X: 8.72,
  RIGHT_COL_W: 3.9,
  INTRO_Y: 2.05,
  INTRO_H: 0.7,
  KEYPOINTS_LABEL_Y: 5.58,
  KEYPOINTS_Y: 5.9,
  KEYPOINTS_H: 0.72,
  TOC_LABEL_Y: 2.05,
  TOC_CARD_Y: 1.9,
  TOC_Y: 2.52,
  TOC_H: 3.55,
  TOC_CARD_H: 4.45,
} as const;

export const SECTION_LAYOUT = {
  BAND_X: 8.68,
  BAND_Y: 0,
  BAND_W: THEME.SLIDE_WIDTH - 8.68,
  BAND_H: THEME.SLIDE_HEIGHT,
  GOLD_STRIPE_Y: 0,
  GOLD_STRIPE_H: 0,
  NUMBER_Y: 1.0,
  NUMBER_H: 0.85,
  TITLE_Y: 1.55,
  TITLE_H: 1.25,
} as const;

export const ENDING_LAYOUT = {
  TEXT_Y: 1.55,
  TEXT_H: 1.45,
  UNDERLINE_Y: 3.1,
} as const;
