import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { generateLecturePptx } from '../dist/index.js';

const lecture = {
  schemaVersion: '1.1',
  documentTitle: 'Jang PPTX Engine Sample',
  direction: 'ltr',
  overview: {
    title: 'Lecture overview',
    introduction: 'A deterministic sample generated by the packaged engine.',
    keyPoints: ['Editable native text', 'Tables and diagrams', 'Automatic pagination'],
  },
  sections: [{
    sectionId: 'sample-section',
    sectionTitle: 'Engine demonstration',
    slides: [{
      slideId: 'sample-content',
      slideTitle: 'Native PowerPoint output',
      slideSubtitle: 'The visual design is preserved while the renderer handles overflow.',
      sourceReferences: ['sample-1'],
      blocks: [
        {
          blockId: 'sample-paragraph',
          type: 'paragraph',
          text: [
            { text: 'Jang ', emphasis: 'bold' },
            { text: 'creates editable PowerPoint content from structured lecture metadata.', emphasis: 'none' },
          ],
          sourceReferences: ['sample-1'],
        },
        {
          blockId: 'sample-bullets',
          type: 'bullets',
          items: ['Native bullet paragraphs', { text: 'Nested editable item', level: 1 }],
          sourceReferences: ['sample-1'],
        },
        {
          blockId: 'sample-table',
          type: 'table',
          label: 'Renderer capabilities',
          headers: ['Capability', 'Status'],
          rows: [
            ['Text and shapes', 'Editable'],
            ['Pagination', 'Deterministic'],
            ['Images', 'Contain or cover'],
          ],
          sourceReferences: ['sample-1'],
        },
      ],
    }, {
      slideId: 'sample-diagram',
      slideTitle: 'Editable pathway',
      slideSubtitle: '',
      sourceReferences: ['sample-2'],
      blocks: [{
        blockId: 'sample-pathway',
        type: 'diagram',
        label: 'Lecture reconstruction pipeline',
        diagramRows: [['Source lecture', 'Gemini metadata', 'Jang renderer'], ['Editable PPTX', 'User review']],
        sourceReferences: ['sample-2'],
      }],
    }],
  }],
  endNote: 'End of sample lecture',
};

const result = await generateLecturePptx(lecture, {}, { strictGeometry: true });
const outputDir = resolve('generated');
await mkdir(outputDir, { recursive: true });
const outputPath = resolve(outputDir, 'jang-pptx-engine-sample.pptx');
await writeFile(outputPath, Buffer.from(await result.blob.arrayBuffer()));
console.log(JSON.stringify({ outputPath, slideCount: result.slideCount, warnings: result.warnings }, null, 2));
